name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: [jruby, '2.7', '2.6', '2.5', '2.4', '2.3']
    env:
      PYGMENTS_VERSION: '~> 1.2.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Ruby
        uses: eregon/use-ruby-action@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: |
          bundle config --local path .bundle/gems
          bundle config --local without docs lint coverage
          # warning output can confuse Powershell in CI, (multi-line scripts & exit codes)
          $env:RUBYOPT = '-W0'
          bundle --jobs 3 --retry 3
      - name: Test
        run: bundle exec ruby -w $(bundle exec ruby -e 'print File.join Gem.bindir, %q(rake)') spec
